### ISSUE TITLE
Can we replace current responseDataType with JSON-LD context?

### ISSUE THREAD

**Issue by newgene** [WebsmartAPI/smartAPI#6]
Currently, the responseDataType is basically a keypath to ID-type-URI pairs:

```
          responseDataType:
            - elementPath: ec
              datatype: 'http://identifiers.org/ec-code/'
            - elementPath: ensembl.gene
              datatype: 'http://identifiers.org/ensembl/'
            - elementPath: ensembl.translation.protein
              datatype: 'http://identifiers.org/ensembl/'
            - elementPath: ensembl.translation.rna
              datatype: 'http://identifiers.org/ensembl/'
            - elementPath: entrezgene
              datatype: 'http://identifiers.org/ncbigene/'
            - elementPath: generif.pubmed
              datatype: 'http://identifiers.org/pubmed/'
            - elementPath: go.bp.evidence
              datatype: 'http://identifiers.org/eco/'
            - elementPath: go.bp.id
              datatype: 'http://identifiers.org/go/'
```
The keypath is flatten in order to provide a simple flat list. 

Can we allow a [JSON-LD](http://json-ld.org) context as the content for responseDataType, so that we can we can provide richer semantic context about the response data?
